apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    rcgroup: group2
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1
    ports:
    - containerPort: 80
      hostPort: 8088
  nodeSelector:
    RDT: enabled
