apiVersion: v1
kind: Namespace
metadata:
  name: rc-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rc-config.default
  namespace: rc-config 
data:
  rc.conf: |
    rdt:
      group1:
        llc: "L3:0=1ff;1=1ff"
        mb: "MB:0=10;1=10"
      group2:
        llc: "L3:0=3ff;1=3ff"
        mb: "MB:0=20;1=20"
      group3:
        llc: "L3:0=7ff;1=7ff"
        mb: "MB:0=30;1=30"
    drc:
      enable: false
      low: ["group1"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rc-config.group.clx
  namespace: rc-config
data:
  rc.conf: |
    rdt:
      group1:
        llc: "L3:0=1ff;1=1ff"
        mb: "MB:0=40;1=40"
      group2:
        llc: "L3:0=3ff;1=3ff"
        mb: "MB:0=50;1=50"
      group3:
        llc: "L3:0=7ff;1=7ff"
        mb: "MB:0=60;1=60"
    drc:
      enable: false
      low: ["group2"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rc-config.group.icx
  namespace: rc-config
data:
  rc.conf: |
    rdt:
      group1:
        llc: "L3:0=1f;1=1f"
      group2:
        llc: "L3:0=3f;1=3f"
      group3:
        llc: "L3:0=ff;1=ff"
    drc:
      enable: true
      low: ["group3"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rc-config.node.izbp1ir6up2903vfrxpae1z
  namespace: rc-config
data:
  rc.conf: |
    rdt:
      group1:
        llc: "L3:0=1ff;1=1ff"
        mb: "MB:0=70;1=70"
      group2:
        llc: "L3:0=3ff;1=3ff"
        mb: "MB:0=80;1=80"
      group3:
        llc: "L3:0=7ff;1=7ff"
        mb: "MB:0=90;1=90"
    drc:
      enable: false
      low: ["group2"]
